# Generated by Django 3.1.8 on 2021-10-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=12)),
                ('team', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], max_length=1)),
                ('task', models.CharField(choices=[('S', 'Spymaster'), ('O', 'Operator')], max_length=1)),
                ('connected_room_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codenames.room')),
            ],
        ),
    ]
