# Generated by Django 3.1.8 on 2021-10-12 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connected_room_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codenames.room')),
            ],
        ),
    ]
