# Generated by Django 3.1.8 on 2021-09-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_key',
        ),
    ]
