# Generated by Django 3.1.8 on 2021-09-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0002_auto_20210918_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=12)),
                ('team', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], max_length=1)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codenames.room')),
            ],
        ),
    ]
