# Generated by Django 3.2.7 on 2021-10-17 15:35

import codenames.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0002_gamewords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='connected_room_key',
            field=models.CharField(blank=True, default=codenames.models.number_default_function, editable=False, max_length=5),
        ),
    ]
