# Generated by Django 3.1.8 on 2021-10-12 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedTeam',
            fields=[
                ('red_team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('red_team_score', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redTeamInfo', to='codenames.game')),
            ],
        ),
        migrations.CreateModel(
            name='BlueTeam',
            fields=[
                ('blue_team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blue_team_score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team_info', to='codenames.game')),
            ],
        ),
    ]
