# Generated by Django 3.2.7 on 2021-10-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_alter_game_connected_room_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamewords',
            name='game_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='gameWords', to='codenames.game'),
            preserve_default=False,
        ),
    ]
