# Generated by Django 3.1.8 on 2021-10-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_blueteam_redteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueteam',
            name='connected_room_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codenames.room'),
        ),
        migrations.AddField(
            model_name='redteam',
            name='connected_room_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codenames.room'),
        ),
    ]
