# Generated by Django 3.1.8 on 2021-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Room',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='room_key',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(max_length=5),
        ),
    ]
