# Generated by Django 3.1.8 on 2021-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(max_length=5),
        ),
    ]
