# Generated by Django 3.2.7 on 2021-10-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0004_gamewords_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redwords',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redWords', to='codenames.gamewords'),
        ),
    ]
