# Generated by Django 3.1.8 on 2021-10-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0004_auto_20211002_1954'),
        ('codenames', '0004_auto_20211004_1656'),
    ]

    operations = [
    ]
