# Generated by Django 3.1.8 on 2021-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0005_merge_20211009_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='room_key',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='connected_room_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codenames.room'),
        ),
    ]
