# Generated by Django 3.1.8 on 2021-10-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0006_auto_20211010_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
