# Generated by Django 3.1.8 on 2021-10-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0007_auto_20211010_2210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('connected_room_key', 'nickname', 'team')},
        ),
    ]
