# Generated by Django 3.1.8 on 2021-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0008_auto_20211011_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=set(),
        ),
    ]
