# Generated by Django 3.1.8 on 2021-10-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0005_userinfo_task'),
        ('codenames', '0009_auto_20211011_1829'),
    ]

    operations = [
    ]
